baseURL = 'https://lgarciavelazquez.github.io/'
languageCode = 'es'
title = 'Mi 3ยบ sitio hugo'
theme =  'PaperMod'

[menu]
[[menu.main]]
identifier = 'posts'
name = 'Publicaciones'
url = '/posts/'


